services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENV: dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - ENV=prod