version: '3.9'

services:
  app:
    build: .
    container_name: chatgpt_text_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn api.server:app --host 0.0.0.0 --port 8000 --reload